# used only for testing in development

version: '2'

services:
  wikiredis:
    image: therickys93/wikiredis
    networks:
      - backbone

  wikicontroller:
    build: .
    environment:
      - "HOST=wikiredis"
    ports:
      - "3000:3000"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge