# used only for testing in development

version: '2'

services:
  redis:
    image: therickys93/wikiredis
    networks:
      - backbone

  controller:
    build: .
    environment:
      - "HOST=redis"
    ports:
      - "3000:3000"
    networks:
      - backbone

  data:
    image: therickys93/wikidata
    environment:
      - REDIS=redis
    networks: 
      - backbone

  proxy:
    image: therickys93/wikiproxy
    ports:
      - "80:80"
    networks:
      - backbone

networks:
  backbone:
    driver: bridge